
<!--Product added success modal-->
<div class="modal fade" id="quick-view" tabindex="-1" role="dialog" aria-labelledby="mdLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="mdLabel" data-qv-product-attribute="name"></h4>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-lg-6">
                <img class="img-responsive" data-qv-product="cover" />
            </div>
            
            <div class="col-lg-6">
                <h3><span data-qv-product="name"></span></h3>
                <h3><?php $this->show('Price'); ?>: <span data-qv-product-attribute="price"></span> <span><?php echo $basket->getCurrency(); ?></span></h3>
                <div class="container-fluid">
                    <article data-qv-product-attribute="description"></article>
                </div>
            </div>
        </div>
      </div>
      
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-chevron-left"></i> <?php $this->show('OK'); ?></a>
      </div>
    </div>
  </div>
</div>
<!--/Product added success modal-->