<?php

use Krystal\Form\Element;

?>


<div class="container">
    
    <h1 class="text-muted"><?php echo $category->getTitle(); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h1>
    <p class="text-muted"><small><?php $this->show('Displayed'); ?>: <?php echo $paginator->getSummary(); ?></small></p>
	
    <article><?php echo $category->getDescription(); ?></article>
    
    <div class="row">
        
        <!-- Filter sidebar -->
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-lg-13"><?php $this->show('Per page'); ?></label>
                <div class="col-lg-13">
                    <?php echo Element::select(null, $ppc->getPerPageCountValues(), $ppc->getPerPageCount(), array('data-category-option' => 'per-page-count', 'class' => 'form-control')); ?>
                </div>
            </div>
            
            <div class="clearfix"></div>
            
            <div class="form-group">
                <label class="col-lg-13"><?php $this->show('Sort method'); ?></label>
                <div class="col-lg-13">
                    <?php echo Element::select(null, $this->translateArray($sorter->getSortingOptions()), $sorter->getSortOption(), array('data-category-option' => 'sort', 'class' => 'form-control')); ?>
                </div>
            </div>
        </div>
        <!-- /Filter sidebar -->
        
        <div class="col-lg-8">
            <?php if (!empty($products)): ?>
            
            <?php $this->loadPartial('product-block'); ?>
            <?php $this->loadPartial('bs-pagination'); ?>
            
            <?php else: ?>
            
            <h2><?php $this->show('No products in this category'); ?></h2>
            <?php endif; ?>
        </div>
    </div>
</div>
